### ISSUE TITLE
May `Sentinel` be subclassed?

### ISSUE THREAD

**Issue by not-my-profile** [taleinat/python-stdlib-sentinels#10]
The specification currently does not specify whether or not the `Sentinel` class may be subclassed.
The reference implementation does not use `@typing.final`, allowing subclasses, which I think does make sense because it allows e.g. the `__str__`  or `__le__` methods of sentinel objects to be customized, which can be very useful.

I think it would make sense to clarify the specification to say that the `Sentinel` class may be subclassed.

**Comment by taleinat** [comment]
(Picking this back up after a long hiatus...)

At some point I thought it would be good to allow subclassing, and even updated the PEP accordingly, but finally decided against it. My reasoning: If added to the stdlib, I think it's crucial for sentinels to be simple and add minimal complexity, including specifically avoiding overly clever uses of sentinels, such as for implementing singleton classes.

Regarding `__str__`, this PEP enables setting the repr of sentinels, which would also be used for their string representation.

Regarding `__le__`, I've just added wording to the PEP explicitly stating that ordering comparisons are not defined for them, and that defining ordering among sentinel values is discouraged, with enums recommended for such use, instead.

Also, consider that a subclass could potentially break the mechanisms used to ensure that sentinel values are singletons; it will be much simpler to make that impossible.
