### ISSUE TITLE
Specific type signatures for each sentinel value

### ISSUE THREAD

**Issue by not-my-profile** [taleinat/python-stdlib-sentinels#11]
I really like the proposed `Sentinel` class because when using an `Enum` for a singleton type it always annoyingly shows up in type signatures and autogenerated documentation.

However I think not supporting `Literal` as mentioned in [Specific type signatures for each sentinel value](https://peps.python.org/pep-0661/#specific-type-signatures-for-each-sentinel-value) is a big mistake, since it would mean `Sentinel` could not actually replace `Enum` if you require the ability to use the type in `Literal` ... which I think is a very common requirement.

Python notably does not support algebraic data types. For example in Rust you could just define:

```rust
enum Submodule {
    Specific(String),
    All,
    AllRecursively,
}
```

the closest you can do in Python is to use the `Union` type, for example `Union[str, Literal[DirectSubmodules, AllSubmodules]]`, now instead of having to abuse `Enum` for this as follows:

```python
class _ModuleSpec(Enum):
    DirectSubmodules = 'DirectSubmodules'
    AllSubmodules = 'AllSubmodules'

DirectSubmodules = _ModuleSpec.DirectSubmodules
AllSubmodules = _ModuleSpec.AllSubmodules
```

(which would result in `_ModuleSpec` showing up in IDE tooltips and autogenerated API documentation and thus potentially confuse users), it would be great if you could instead just do:

```python
DirectSubmodules = Sentinel('DirectSubmodules')
AllSubmodules = Sentinel('AllSubmodules')
``` 

and still be able to use `Literal[DirectSubmodules, AllSubmodules]`.

The PEP mentions that `Literal` support has been dropped from the PEP due to [concerns voiced on the mailing list](https://mail.python.org/archives/list/typing-sig@python.org/thread/NDEJ7UCDPINP634GXWDARVMTGDVSNBKV/#LVCPTY26JQJW7NKGKGAZXHQKWVW7GOGL). While I cannot really comment on the challenges of special casing `Literal`, I think this additional complexity would definitely be worth it to make `Sentinel` as useful as `Enum` and allow it to replace it for cases where you do not actually want to introduce an enum type.

**Comment by JelleZijlstra** [comment]
You don't say what concrete problems this would solve. I think both the PEP and the linked typing-sig discussion got a bit stuck in disagreement over how sentinels should be defined, but my preference (second message in the thread), which I still stand by, is to make sentinels directly usable as types. In your case, if you want to accept either `str` or your two sentinels, you would write `str | DirectSubmodules | AllSubmodules`.

**Comment by not-my-profile** [comment]
Oh that would actually work great for me ... I created this issue because I understood the [Specific type signatures for each sentinel value](https://peps.python.org/pep-0661/#specific-type-signatures-for-each-sentinel-value) section of the PEP to say that value-specific types wouldn't be supported at all. Am I misunderstanding the PEP? Reading the section again it still seems to imply that `str | DirectSubmodules | AllSubmodules` wouldn't be supported.

**Comment by taleinat** [comment]
(Picking this back up after a long hiatus...)

I ended up going with `Literal[...]` for type signatures.

However, I would consider it somewhat a misuse to use sentinels to achieve algebraic data types. An enum of some sort would seem to be better, as it makes it clear that the values are related to each other.

FWIW, I haven't tried it yet, but it should be possible to override the repr of an Enum via a metaclass.
