### ISSUE TITLE
Question on sentinel instantiation

### ISSUE THREAD

**Issue by idlesign** [taleinat/python-stdlib-sentinels#3]
Hi,

Just wonder what'd happen to `a is sentinel` checks if a user is messing with relative/absolute imports or sentinels are spawned in different threads.

I've have had a good time years ago while debugging a similar case of `sentinel = object()` and `is` checks, which lead me to `sentinel = tuple()` approach.

**Comment by taleinat** [comment]
> Just wonder what'd happen to `a is sentinel checks` if a user is messing with relative/absolute imports

Users messing with imports have plenty of other things to worry about, I think. Is there a specific case you have in mind where something like this could behave in unexpected ways?

> or sentinels are spawned in different threads.

These sentinels would usually be created during module import, during which thread safety issues are less of an issue. In other cases, one could sentinel creation with a mutex, just like anything else with side-effects that needs to be thread-safe.

> I've have had a good time years ago while debugging a similar case of `sentinel = object()` and `is` checks, which lead me to `sentinel = tuple()` approach.

Could you elaborate on this? How is `sentinel = tuple()` better than `sentinel = object()`?

**Comment by idlesign** [comment]
> Is there a specific case you have in mind where something like this could behave in unexpected ways?

As far as I remember, I've encountered identity check related issues on web-related setups with forking and multiprocessing involved.

> Could you elaborate on this? How is sentinel = tuple() better than sentinel = object()?

It's as simple as

```
>>> tuple() is tuple()
True
>>> object() is object()
False
```
without mutex etc. stuff.

**Comment by RonnyPfannschmidt** [comment]
a key issue here is, that one is no longer able to keep apart sentinels of different libraries, the sentinel of another library is  not necessarily a good idea to consider as a sentinel somewhere else

**Comment by idlesign** [comment]
> a key issue here is, that one is no longer able to keep apart sentinels of different libraries, 

I won't consider it to be an issue. There should be legitimate cases when the same primitive shared across different code uses is a perfect fit. E.g.: `def do(arg=UNSET)` seems to be one of them, and I'd eagerly import UNSET from stdlib as a singletone and use in my libraries.

**Comment by taleinat** [comment]
> Just wonder what'd happen to a is sentinel checks if a user is messing with relative/absolute imports

Only the module where the sentinel is created, and its name, should matter. Relative/absolute imports shouldn't affect this.

> or sentinels are spawned in different threads.

This reference implementation is thread-safe.

Much of this reference implementation specifically addresses such use cases. Issues with multiple processes, threads, copying and pickling+unpickling should all be handled seamlessly, with identity comparisons continuing to work as expected. **If you find a case where this doesn't work, that's a bug.**

Similarly, this makes both getting the same sentinel consistently and creating separate ones simple. If you define a sentinel in a module and import it elsewhere, it will be the same sentinel. If you create identically named sentinels in different places in the same module, they will be identical. If you define identically named sentinels in different modules, they will be different.
