### ISSUE TITLE
Add to builtins

### ISSUE THREAD

**Issue by bharel** [taleinat/python-stdlib-sentinels#5]
Hey Tal,

Instead of creating a module with a single function, and since sentinel is used 468 times in 58 different python files just in the standard library, I believe it justifies adding it to the builtins.
![image](https://user-images.githubusercontent.com/742359/129495198-70f2dec2-ba28-46f6-9201-225aead3103b.png)

The usage of sentinel values is vast, and almost every Python module I write or contribute to has created at least one sentinel value.

Importing the module just about everywhere sounds a bit counter-productive, as creating sentinel objects should be as simple as creating a string, a "None" object, or an integer. Plus, I do not see how the "sentinels" module grows to have more than the single "sentinel" class. No matter how it grows, it'll break the uniqueness and thus one of the requirements of a sentinel value.

Lots of love ❤️ 
Bar Harel.

**Comment by tusharsadhwani** [comment]
Hey @bharel 

This is a reference implementation. The goal has always been to get this into stdlib. See: https://peps.python.org/pep-0661/

**Comment by bharel** [comment]
Not stdlib, built-ins. It is common enough to justify it :-)
The proposal constantly talks about stdlib and I believe it should take a slightly different approach.

**Comment by taleinat** [comment]
Thanks for the suggestion @bharel!

I disagree that this should be added to the built-ins, though. And even if I agreed, I very much doubt that that would be accepted; there would need to be a very strong argument in favor of adding something to Python's built-ins; much stronger than the one brought forth here.

The reason that such a strong argument would be needed is that adding a built-in inherently breaks backwards-compatibility: Every built-in is a name that everyone must be careful not to override with names of variables, classes, modules etc.
