### ISSUE TITLE
Singular or plural for the module name

### ISSUE THREAD

**Issue by not-my-profile** [taleinat/python-stdlib-sentinels#9]
The [Specification section of PEP 661](https://peps.python.org/pep-0661/#specification) currently says:

> A new `Sentinel` class will be added to a new `sentinels` module.

Note "sentinels" in plural but goes on with a code example showing `sentinel` in singular:

> ```python
>  >>> from sentinel import Sentinel
>  ```

While the latter appears to be a typo, I think singular would actually be preferable to plural to be consistent with the [`enum` module](https://docs.python.org/3/library/enum.html), which is called `enum` instead of `enums`, so I think the sentinel module should also be called `sentinel` instead of `sentinels`.

**Comment by taleinat** [comment]
Thanks for noticing and notifying me of this! This has been fixed. (Indeed, the name of the module should be plural.)
